const mongoose = require("mongoose");
const {Schema}=mongoose;

const user = new Schema({
    telefono:{
        required:true,
        type:Number,
        minlength:1,
        maxlength:10
    },
    nombre:{
        required:true,
        type:String,
        minlength:1,
        maxlength:30
    },
    apellidos:{
        required:true,
        type:String,
        minlength:1,
        maxlength:50
    },
    rfc:{
        required:true,
        type:String,
        minlength:1,
        maxlength:60
    },
    direccion:{
        required:true,
        type:String,
        minlength:1,
        maxlength:40
    },
    fechaNacimiento:{
        required:true,
        type:String
    },
    email:{
        required:true,
        type:String,
        minlength:1,
        maxlength:30
    },
    password:{
        required:true,
        type:String,
        minlength:1,
        maxlength:60
    },
    id_centro_acopio:{
        required:false,
        type:String,
        minlength:1,
        maxlength:70
    }
});

module.exports={
    model:mongoose.model('user',user),
    user
}